# .goreleaser.yml
# Build customization
builds:
  - binary: foomo-releaser
    main:   ./releaser.go
    env:
        - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# .goreleaser.yml
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

brew:
  # Reporitory to push the tap to.
  github:
    owner: foomo
    name: homebrew-foomo-releaser

  caveats: "foomo-releaser -t {TOKEN} -d {DIRECTORY} -v {VERSION}"
  homepage: "https://github.com/foomo/foomo-releaser"
  description: "CLI Utility to generate releases for foomo-related projects"